services:
  - type: web
    name: heart-disease-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      cd backend &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn backend.wsgi:application
